import assert from 'node:assert/strict';
import { randomBytes, createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const origin = process.env.WICCERS_TEST_ORIGIN || 'http://localhost:3000';
const ids = [], posts = [];
const suffix = randomBytes(4).toString('hex');
const testAddress = `integration-${suffix}`;
const secret = randomBytes(20).toString('hex');
const request = async (endpoint, body, cookie, extra = {}) => {
  const response = await fetch(origin + endpoint, { method: body ? 'POST' : 'GET', headers: { ...(body ? {'Content-Type':'application/json',Origin:origin} : {}), 'x-forwarded-for':testAddress, ...(cookie ? {Cookie:cookie}:{}), ...extra}, body:body ? JSON.stringify(body) : undefined });
  return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};
};
try {
  const environment = await request('/api/wiccers/auth');
  assert.equal(environment.data.storage,'local','Integration fixtures must only run against local development storage');
  const first = await request('/api/wiccers/auth',{action:'register',name:`qa_sage_${suffix}`,password:secret});
  assert.equal(first.status,200); ids.push(first.data.user.id);
  assert.ok(first.cookie.includes('wiccers_session='));
  assert.equal('passwordHash' in first.data.user,false);
  const second = await request('/api/wiccers/auth',{action:'register',name:`qa_moon_${suffix}`,password:secret});
  assert.equal(second.status,200); ids.push(second.data.user.id);
  assert.equal((await request('/api/wiccers/auth',{action:'register',name:`QA_SAGE_${suffix}`,password:secret})).status,409);
  assert.equal((await request('/api/wiccers/auth',{action:'login',name:`qa_sage_${suffix}`,password:'incorrect-password'})).status,401);
  assert.equal((await request('/api/wiccers',{action:'post',content:'Unauthorized'})).status,401);
  assert.equal((await request('/api/wiccers',{action:'post',content:'Cross origin'},first.cookie,{Origin:'https://example.com'})).status,403);
  assert.equal((await request('/api/wiccers',{action:'post',content:'x'.repeat(501)},first.cookie)).status,400);
  const posted = await request('/api/wiccers',{action:'post',content:`Integration test #constellation_${suffix}`,authorId:second.data.user.id},first.cookie);
  assert.equal(posted.status,201);posts.push(posted.data.id);
  let feed = await request('/api/wiccers',undefined,first.cookie);
  const post = feed.data.posts.find(p=>p.id===posted.data.id);
  assert.equal(post.author.id,first.data.user.id,'The server, not the request, controls authorship');
  assert.equal((await request('/api/wiccers',{action:'like',postId:post.id},first.cookie)).data.count,1);
  assert.equal((await request('/api/wiccers',{action:'like',postId:post.id},first.cookie)).data.count,0);
  await request('/api/wiccers',{action:'bookmark',postId:post.id},second.cookie);
  assert.ok((await request('/api/wiccers?view=bookmarks',undefined,second.cookie)).data.posts.some(p=>p.id===post.id));
  assert.ok(!(await request('/api/wiccers?view=bookmarks',undefined,first.cookie)).data.posts.some(p=>p.id===post.id));
  await request('/api/wiccers',{action:'follow',memberId:first.data.user.id},second.cookie);
  assert.ok((await request('/api/wiccers?view=following',undefined,second.cookie)).data.posts.some(p=>p.id===post.id));
  const publicFollowers = await request(`/api/wiccers?followers=${first.data.user.id}`);
  assert.equal(publicFollowers.status,200,'Followers are visible without signing in');
  assert.deepEqual(publicFollowers.data.followers.map(member=>member.id),[second.data.user.id]);
  assert.equal(publicFollowers.data.profile.followers,1);
  assert.equal('passwordHash' in publicFollowers.data.followers[0],false);
  assert.equal('key' in publicFollowers.data.followers[0],false);
  assert.deepEqual((await request(`/api/wiccers?followers=${second.data.user.id}`)).data.followers,[]);
  assert.equal((await request('/api/wiccers?followers=nonexistent-profile')).status,404);
  await request('/api/wiccers',{action:'follow',memberId:first.data.user.id},second.cookie);
  assert.deepEqual((await request(`/api/wiccers?followers=${first.data.user.id}`)).data.followers,[],'Unfollowing updates the public list');
  await request('/api/wiccers',{action:'follow',memberId:first.data.user.id},second.cookie);
  assert.equal((await request('/api/wiccers',{action:'repost',postId:post.id},second.cookie)).data.count,1);
  const reply = await request('/api/wiccers',{action:'post',content:'Test reply',parentId:post.id},second.cookie);assert.equal(reply.status,201);posts.push(reply.data.id);
  assert.equal((await request(`/api/wiccers?thread=${post.id}`,undefined,first.cookie)).data.posts[0].id,reply.data.id);
  await request('/api/wiccers',{action:'profile',bio:'A test profile',color:'violet'},first.cookie);
  assert.equal((await request(`/api/wiccers?profile=${first.data.user.id}`,undefined,first.cookie)).data.profile.bio,'A test profile');
  const renamed = `qa_changed_${suffix}`;
  assert.equal((await request('/api/wiccers',{action:'profile',name:`qa_moon_${suffix}`,bio:'Should not save',color:'rose'},first.cookie)).status,409);
  assert.equal((await request('/api/wiccers',{action:'profile',name:'bad name!',bio:'Should not save',color:'rose'},first.cookie)).status,400);
  assert.equal((await request('/api/wiccers',{action:'profile',name:renamed,bio:'A test profile',color:'violet'})).status,401);
  const rename = await request('/api/wiccers',{action:'profile',name:`  ${renamed.toUpperCase()}  `,bio:'A test profile',color:'violet',memberId:second.data.user.id},first.cookie);
  assert.equal(rename.status,200); assert.equal(rename.data.user.id,first.data.user.id);
  assert.equal(rename.data.user.name,renamed.toUpperCase());
  assert.equal((await request('/api/wiccers/auth',undefined,first.cookie)).data.user.name,renamed.toUpperCase(),'Renaming preserves existing sessions');
  assert.equal((await request(`/api/wiccers?profile=${first.data.user.id}`)).data.posts.find(p=>p.id===post.id).author.name,renamed.toUpperCase(),'Existing posts show the updated author');
  assert.equal((await request(`/api/wiccers?followers=${first.data.user.id}`)).data.followers.length,1,'Renaming preserves followers');
  assert.equal((await request('/api/wiccers/auth',{action:'login',name:`qa_sage_${suffix}`,password:secret})).status,401,'The old username no longer signs in');
  assert.equal((await request('/api/wiccers',{action:'delete',postId:post.id},second.cookie)).status,403);
  assert.equal((await request('/api/wiccers',{action:'delete',postId:post.id},first.cookie)).status,200);
  assert.equal((await request(`/api/wiccers?thread=${post.id}`,undefined,second.cookie)).data.posts.length,0,'Deleting a root removes its replies');
  const ownRoot = await request('/api/wiccers',{action:'post',content:'Account deletion test'},second.cookie); assert.equal(ownRoot.status,201); posts.push(ownRoot.data.id);
  const otherReply = await request('/api/wiccers',{action:'post',content:'Reply by another member',parentId:ownRoot.data.id},first.cookie); assert.equal(otherReply.status,201); posts.push(otherReply.data.id);
  const retained = await request('/api/wiccers',{action:'post',content:'This post must survive'},first.cookie); assert.equal(retained.status,201); posts.push(retained.data.id);
  const ownReply = await request('/api/wiccers',{action:'post',content:'Delete just this reply',parentId:retained.data.id},second.cookie); assert.equal(ownReply.status,201); posts.push(ownReply.data.id);
  assert.equal((await request('/api/wiccers',{action:'delete',postId:ownReply.data.id},first.cookie)).status,403);
  assert.equal((await request('/api/wiccers',{action:'delete',postId:ownReply.data.id},second.cookie)).status,200);
  assert.equal((await request(`/api/wiccers?thread=${retained.data.id}`)).data.posts.length,0,'Deleting a comment preserves its parent');
  const accountReply = await request('/api/wiccers',{action:'post',content:'Account-owned comment',parentId:retained.data.id},second.cookie); assert.equal(accountReply.status,201); posts.push(accountReply.data.id);
  await request('/api/wiccers',{action:'like',postId:retained.data.id},second.cookie);
  await request('/api/wiccers',{action:'repost',postId:retained.data.id},second.cookie);
  await request('/api/wiccers',{action:'bookmark',postId:ownRoot.data.id},first.cookie);
  await request('/api/wiccers',{action:'follow',memberId:second.data.user.id},first.cookie);
  const secondSession = await request('/api/wiccers/auth',{action:'login',name:`qa_moon_${suffix}`,password:secret}); assert.equal(secondSession.status,200);
  assert.equal((await request('/api/wiccers/auth',{action:'delete-account',password:secret})).status,401);
  assert.equal((await request('/api/wiccers/auth',{action:'delete-account',password:secret},second.cookie,{Origin:'https://example.com'})).status,403);
  assert.equal((await request('/api/wiccers/auth',{action:'delete-account',password:'incorrect'},second.cookie)).status,401);
  assert.equal((await request('/api/wiccers/auth',undefined,second.cookie)).data.user.id,second.data.user.id,'Incorrect password must not delete the account');
  const deletedAccount = await request('/api/wiccers/auth',{action:'delete-account',password:secret,memberId:first.data.user.id},second.cookie);
  assert.equal(deletedAccount.status,200); assert.equal(deletedAccount.data.deleted,true);
  assert.equal(deletedAccount.cookie,'wiccers_session=');
  assert.equal((await request('/api/wiccers/auth',undefined,second.cookie)).data.user,null);
  assert.equal((await request('/api/wiccers/auth',undefined,secondSession.cookie)).data.user,null,'Account deletion invalidates every session');
  assert.equal((await request('/api/wiccers/auth',undefined,first.cookie)).data.user.id,first.data.user.id,'A supplied memberId cannot delete a different account');
  assert.equal((await request('/api/wiccers/auth',{action:'login',name:`qa_moon_${suffix}`,password:secret})).status,401);
  const remaining = await request(`/api/wiccers?profile=${first.data.user.id}`);
  const survivor = remaining.data.posts.find(p=>p.id===retained.data.id);
  assert.ok(survivor); assert.equal(survivor.likes,0); assert.equal(survivor.reposts,0); assert.equal(survivor.replies,0);
  assert.equal((await request(`/api/wiccers?thread=${ownRoot.data.id}`)).data.posts.length,0,'Account deletion removes replies under its roots');
  assert.equal((await request(`/api/wiccers?followers=${second.data.user.id}`)).status,404);
  assert.deepEqual((await request(`/api/wiccers?followers=${first.data.user.id}`)).data.followers,[]);
  assert.ok(!(await request('/api/wiccers?view=bookmarks',undefined,first.cookie)).data.posts.some(p=>p.id===ownRoot.data.id));
  const stored = JSON.parse(await readFile(path.resolve('.local/wiccers.json'),'utf8'));
  assert.ok(!stored.posts.some(p=>p.authorId===second.data.user.id));
  assert.ok(!stored.follows.some(f=>f.from===second.data.user.id||f.to===second.data.user.id));
  assert.ok(!stored.bookmarks.some(b=>b.memberId===second.data.user.id));
  const login = await request('/api/wiccers/auth',{action:'login',name:renamed,password:secret});assert.equal(login.status,200);
  await request('/api/wiccers/auth',{action:'logout'},login.cookie);
  assert.equal((await request('/api/wiccers/auth',undefined,login.cookie)).data.user,null,'Logout invalidates the server session');
  console.log('PASS: community integration, username changes, ownership checks, comment deletion, password-confirmed account deletion, cascade cleanup, and all-session invalidation.');
} finally {
  // Clean only this run's disposable local fixtures, preserving unrelated data.
  const file = path.resolve('.local/wiccers.json');
  const state = JSON.parse(await readFile(file,'utf8'));
  assert.ok(state.members.filter(m=>ids.includes(m.id)).every(m=>m.name.toLowerCase().endsWith(suffix)),'Cleanup is limited to identified test accounts');
  state.members=state.members.filter(m=>!ids.includes(m.id));
  state.posts=state.posts.filter(p=>!ids.includes(p.authorId));
  state.sessions=state.sessions.filter(s=>!ids.includes(s.memberId));
  state.follows=state.follows.filter(f=>!ids.includes(f.from)&&!ids.includes(f.to));
  state.bookmarks=state.bookmarks.filter(b=>!ids.includes(b.memberId)&&!posts.includes(b.postId));
  const authKey = `auth:${createHash('sha256').update(testAddress).digest('hex')}`;
  state.limits=state.limits.filter(l=>!ids.some(id=>l.key.includes(id))&&!l.key.endsWith(suffix)&&l.key!==authKey);
  await writeFile(file,JSON.stringify(state));
}
