import assert from 'node:assert/strict';
import { randomBytes, createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const origin = process.env.WICCERS_TEST_ORIGIN || 'http://localhost:3000';
const ids = [], posts = [];
const suffix = randomBytes(4).toString('hex');
const testAddress = `integration-${suffix}`;
const secret = randomBytes(20).toString('hex');
const request = async (endpoint, body, cookie, extra = {}) => {
  const response = await fetch(origin + endpoint, { method: body ? 'POST' : 'GET', headers: { ...(body ? {'Content-Type':'application/json',Origin:origin} : {}), 'x-forwarded-for':testAddress, ...(cookie ? {Cookie:cookie}:{}), ...extra}, body:body ? JSON.stringify(body) : undefined });
  return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};
};
try {
  const environment = await request('/api/wiccers/auth');
  assert.equal(environment.data.storage,'local','Integration fixtures must only run against local development storage');
  const first = await request('/api/wiccers/auth',{action:'register',name:`qa_sage_${suffix}`,password:secret});
  assert.equal(first.status,200); ids.push(first.data.user.id);
  assert.ok(first.cookie.includes('wiccers_session='));
  assert.equal('passwordHash' in first.data.user,false);
  const second = await request('/api/wiccers/auth',{action:'register',name:`qa_moon_${suffix}`,password:secret});
  assert.equal(second.status,200); ids.push(second.data.user.id);
  assert.equal((await request('/api/wiccers/auth',{action:'register',name:`QA_SAGE_${suffix}`,password:secret})).status,409);
  assert.equal((await request('/api/wiccers/auth',{action:'login',name:`qa_sage_${suffix}`,password:'incorrect-password'})).status,401);
  assert.equal((await request('/api/wiccers',{action:'post',content:'Unauthorized'})).status,401);
  assert.equal((await request('/api/wiccers',{action:'post',content:'Cross origin'},first.cookie,{Origin:'https://example.com'})).status,403);
  assert.equal((await request('/api/wiccers',{action:'post',content:'x'.repeat(501)},first.cookie)).status,400);
  const posted = await request('/api/wiccers',{action:'post',content:`Integration test #constellation_${suffix}`,authorId:second.data.user.id},first.cookie);
  assert.equal(posted.status,201);posts.push(posted.data.id);
  let feed = await request('/api/wiccers',undefined,first.cookie);
  const post = feed.data.posts.find(p=>p.id===posted.data.id);
  assert.equal(post.author.id,first.data.user.id,'The server, not the request, controls authorship');
  assert.equal((await request('/api/wiccers',{action:'like',postId:post.id},first.cookie)).data.count,1);
  assert.equal((await request('/api/wiccers',{action:'like',postId:post.id},first.cookie)).data.count,0);
  await request('/api/wiccers',{action:'bookmark',postId:post.id},second.cookie);
  assert.ok((await request('/api/wiccers?view=bookmarks',undefined,second.cookie)).data.posts.some(p=>p.id===post.id));
  assert.ok(!(await request('/api/wiccers?view=bookmarks',undefined,first.cookie)).data.posts.some(p=>p.id===post.id));
  await request('/api/wiccers',{action:'follow',memberId:first.data.user.id},second.cookie);
  assert.ok((await request('/api/wiccers?view=following',undefined,second.cookie)).data.posts.some(p=>p.id===post.id));
  const publicFollowers = await request(`/api/wiccers?followers=${first.data.user.id}`);
  assert.equal(publicFollowers.status,200,'Followers are visible without signing in');
  assert.deepEqual(publicFollowers.data.followers.map(member=>member.id),[second.data.user.id]);
  assert.equal(publicFollowers.data.profile.followers,1);
  assert.equal('passwordHash' in publicFollowers.data.followers[0],false);
  assert.equal('key' in publicFollowers.data.followers[0],false);
  assert.deepEqual((await request(`/api/wiccers?followers=${second.data.user.id}`)).data.followers,[]);
  assert.equal((await request('/api/wiccers?followers=nonexistent-profile')).status,404);
  await request('/api/wiccers',{action:'follow',memberId:first.data.user.id},second.cookie);
  assert.deepEqual((await request(`/api/wiccers?followers=${first.data.user.id}`)).data.followers,[],'Unfollowing updates the public list');
  await request('/api/wiccers',{action:'follow',memberId:first.data.user.id},second.cookie);
  assert.equal((await request('/api/wiccers',{action:'repost',postId:post.id},second.cookie)).data.count,1);
  const reply = await request('/api/wiccers',{action:'post',content:'Test reply',parentId:post.id},second.cookie);assert.equal(reply.status,201);posts.push(reply.data.id);
  assert.equal((await request(`/api/wiccers?thread=${post.id}`,undefined,first.cookie)).data.posts[0].id,reply.data.id);
  await request('/api/wiccers',{action:'profile',bio:'A test profile',color:'violet'},first.cookie);
  assert.equal((await request(`/api/wiccers?profile=${first.data.user.id}`,undefined,first.cookie)).data.profile.bio,'A test profile');
  assert.equal((await request('/api/wiccers',{action:'delete',postId:post.id},second.cookie)).status,403);
  assert.equal((await request('/api/wiccers',{action:'delete',postId:post.id},first.cookie)).status,200);
  assert.equal((await request(`/api/wiccers?thread=${post.id}`,undefined,second.cookie)).data.posts.length,0,'Deleting a root removes its replies');
  const login = await request('/api/wiccers/auth',{action:'login',name:`qa_sage_${suffix}`,password:secret});assert.equal(login.status,200);
  await request('/api/wiccers/auth',{action:'logout'},login.cookie);
  assert.equal((await request('/api/wiccers/auth',undefined,login.cookie)).data.user,null,'Logout invalidates the server session');
  console.log('PASS: signup, unique names, password verification, session invalidation, origins, post bounds, trusted authorship, like toggling, private bookmarks, following, public follower lists, reposts, replies, profiles, and deletion ownership.');
} finally {
  // Clean only this run's disposable local fixtures, preserving unrelated data.
  const file = path.resolve('.local/wiccers.json');
  const state = JSON.parse(await readFile(file,'utf8'));
  assert.ok(ids.every(id=>state.members.some(m=>m.id===id&&m.name.endsWith(suffix))),'Cleanup is limited to identified test accounts');
  state.members=state.members.filter(m=>!ids.includes(m.id));
  state.posts=state.posts.filter(p=>!ids.includes(p.authorId));
  state.sessions=state.sessions.filter(s=>!ids.includes(s.memberId));
  state.follows=state.follows.filter(f=>!ids.includes(f.from)&&!ids.includes(f.to));
  state.bookmarks=state.bookmarks.filter(b=>!ids.includes(b.memberId)&&!posts.includes(b.postId));
  const authKey = `auth:${createHash('sha256').update(testAddress).digest('hex')}`;
  state.limits=state.limits.filter(l=>!ids.some(id=>l.key.includes(id))&&!l.key.endsWith(suffix)&&l.key!==authKey);
  await writeFile(file,JSON.stringify(state));
}
